class UnitSymbolType(Enum, IComparable, IFormattable, IConvertible):
    """
    The unit symbol displayed in the formatted string representation of a number to indicate the units of the value.
    
    enum UnitSymbolType, values: UST_ACRES (701), UST_AMPERE (6901), UST_ATM (5401), UST_BAHT (17510), UST_BAR (5501), UST_BTU (3101), UST_BTU_PER_F (18601), UST_BTU_PER_H (4201), UST_BTU_PER_H_CU_FT (16701), UST_BTU_PER_H_FT_DEGREE_F (23101), UST_BTU_PER_H_SQ_FT (16601), UST_BTU_PER_H_SQ_FT_DEGREE_F (15501), UST_BTU_PER_LB (23301), UST_BTU_PER_LB_DEGREE_F (23201), UST_BTU_PER_S (4101), UST_CAL (3201), UST_CAL_PER_S (4301), UST_CD (8101), UST_CD_PER_SQ_M (8001), UST_CF (1301), UST_CFM (6302), UST_CFM_PER_CF (16902), UST_CFM_PER_CU_FT (16901), UST_CFM_PER_SF (15602), UST_CFM_PER_SQ_FT (15601), UST_CFM_PER_TON (17101), UST_CHINESE_HONG_KONG_SAR (17506), UST_CM (101), UST_CM_CARET_2 (2102), UST_CM_CARET_3 (2402), UST_CM_PER_MIN (6201), UST_CM_SUP_2 (2101), UST_CM_SUP_3 (2401), UST_CM_SUP_4 (20001), UST_CM_SUP_6 (20501), UST_CMH (6602), UST_CMS (6502), UST_COLON_10 (15801), UST_COLON_12 (15901), UST_CP (13101), UST_CPS (7601), UST_CU_FT_PER_MIN (6301), UST_CU_M_PER_H (6601), UST_CU_M_PER_S (6501), UST_CY (1001), UST_DA_N (8801), UST_DA_N_DASH_M (11201), UST_DA_N_DASH_M_PER_M (14001), UST_DA_N_PER_M (9601), UST_DA_N_PER_M_SUP_2 (10401), UST_DEGREE_C (5701), UST_DEGREE_C_DIFFERENCE (24401), UST_DEGREE_F (5601), UST_DEGREE_F_DIFFERENCE (24301), UST_DEGREE_R (5901), UST_DEGREE_R_DIFFERENCE (24601), UST_DEGREE_SYMBOL (1501), UST_DELTA_DEGREE_C (24402), UST_DELTA_DEGREE_F (24302), UST_DELTA_DEGREE_R (24602), UST_DELTA_KELVIN (24502), UST_DM (23601), UST_DOLLAR (17501), UST_DONG (17509), UST_EURO_PREFIX (17503), UST_EURO_SUFFIX (17502), UST_FC (7801), UST_FEET_OF_WATER (12803), UST_FEET_OF_WATER_PER_100FT (12703), UST_FL (7901), UST_FL_LOWERCASE (7902), UST_FOOT_SINGLE_QUOTE (302), UST_FPM (6002), UST_FPS (13202), UST_FT (303), UST_FT_CARET_2 (1103), UST_FT_CARET_3 (1303), UST_FT_OF_WATER (12802), UST_FT_OF_WATER_PER_100FT (12702), UST_FT_PER_KIP (12001), UST_FT_PER_MIN (6001), UST_FT_PER_S (13201), UST_FT_PER_SQ_S (19501), UST_FT_SUP_2 (1102), UST_FT_SUP_2_PER_KIP (12201), UST_FT_SUP_3 (1302), UST_FT_SUP_3_PER_KIP (12401), UST_FT_SUP_4 (19701), UST_FT_SUP_6 (20201), UST_FTC (7802), UST_FTH2O (12801), UST_FTH2O_PER_100FT (12701), UST_FTL (7903), UST_GAL (2701), UST_GAL_PER_H (6801), UST_GAL_PER_MIN (6701), UST_GPH (6802), UST_GPM (6702), UST_GR_PER_H_SQ_FT_IN_HG (23401), UST_GRAD (21501), UST_H (22001), UST_H_SQ_FT_DEGREE_F_PER_BTU (18401), UST_HECTARES (801), UST_HP (8601), UST_HZ (7501), UST_IN (602), UST_IN_CARET_2 (2002), UST_IN_CARET_3 (2302), UST_IN_HG (5201), UST_IN_PER_SQ_S (19401), UST_IN_SUP_2 (2001), UST_IN_SUP_3 (2301), UST_IN_SUP_4 (19801), UST_IN_SUP_6 (20301), UST_IN_WG (4701), UST_IN_WG_PER_100FT (3701), UST_INCH_DOUBLE_QUOTE (601), UST_INV_DEGREE_C (13801), UST_INV_DEGREE_F (13701), UST_INV_K_N (12501), UST_INV_KIP (12601), UST_J_PER_G (22801), UST_J_PER_G_CELSIUS (22701), UST_J_PER_KELVIN (18701), UST_J_PER_KG_CELSIUS (23701), UST_JOULE (3401), UST_K_N (8901), UST_K_N_DASH_M (11301), UST_K_N_DASH_M_PER_M (14101), UST_K_N_M_PER_DEGREE (15101), UST_K_N_M_PER_DEGREE_PER_M (15301), UST_K_N_PER_CM_SUP_2 (17801), UST_K_N_PER_M (9701), UST_K_N_PER_M_SUP_2 (10501), UST_K_N_PER_MM_SUP_2 (18001), UST_KCAL (3301), UST_KCAL_PER_S (4401), UST_KELVIN (5801), UST_KELVIN_DIFFERENCE (24501), UST_KG_PER_CU_M (2801), UST_KGF (9201), UST_KGF_DASH_M (11601), UST_KGF_DASH_M_PER_M (14401), UST_KGF_PER_M (10001), UST_KGF_PER_M_SUP_2 (10801), UST_KGM (18901), UST_KGM_PER_M (21201), UST_KGM_PER_SQ_M (22401), UST_KILOAMPERE (7001), UST_KILOPASCAL (4901), UST_KILOVOLT (7301), UST_KILOVOLTAMPERE (8501), UST_KILOWATT (4001), UST_KIP (9101), UST_KIP_DASH_FT (11501), UST_KIP_DASH_FT_PER_FT (14301), UST_KIP_FT_PER_DEGREE (15001), UST_KIP_FT_PER_DEGREE_PER_FT (15201), UST_KIP_PER_FT (9901), UST_KIP_PER_IN_SUP_3 (13601), UST_KIP_PER_SQ_FT (10702), UST_KIP_PER_SQ_IN (13302), UST_KIPS_PER_CU_FT (14901), UST_KIPS_PER_IN (14801), UST_KJ (22301), UST_KJ_PER_KELVIN (18801), UST_KM_PER_H (22101), UST_KM_PER_SQ_S (19301), UST_KN_PER_M_SUP_3 (13401), UST_KRONER (17511), UST_KSF (10701), UST_KSI (13301), UST_KWH (3501), UST_L (2601), UST_L_PER_M (24201), UST_L_PER_S (6401), UST_L_PER_S_CU_M (17001), UST_L_PER_S_KW (17201), UST_L_PER_S_SQ_M (15702), UST_LB_FORCE (9401), UST_LB_FORCE_DASH_FT (11801), UST_LB_FORCE_DASH_FT_PER_FT (14601), UST_LB_FORCE_PER_CU_FT (13501), UST_LB_FORCE_PER_FT (10201), UST_LB_FORCE_PER_FT_H (14701), UST_LB_FORCE_PER_FT_S (13001), UST_LB_FORCE_PER_SQ_FT (11002), UST_LB_FORCE_PER_SQ_IN (5102), UST_LB_MASS (19101), UST_LB_MASS_PER_CU_FT (2901), UST_LB_MASS_PER_CU_IN (3001), UST_LB_MASS_PER_FT (21301), UST_LBF (9402), UST_LBF_DASH_FT (11802), UST_LBF_DASH_FT_PER_FT (14602), UST_LBF_PER_CU_FT (13502), UST_LBF_PER_FT (10202), UST_LBF_PER_SQ_FT (11003), UST_LBF_PER_SQ_IN (5105), UST_LBM (19102), UST_LBM_PER_CU_FT (2902), UST_LBM_PER_CU_IN (3002), UST_LBM_PER_FT (21302), UST_LBM_PER_FT_H (14702), UST_LBM_PER_FT_S (13002), UST_LBM_PER_SQ_FT (22501), UST_LF (301), UST_LM (8301), UST_LM_PER_W (17601), UST_LPM (24202), UST_LPS (6402), UST_LPS_PER_SQ_M (15701), UST_LX (7701), UST_M (1), UST_M_CARET_2 (1202), UST_M_CARET_3 (1402), UST_M_N (9001), UST_M_N_DASH_M (11401), UST_M_N_DASH_M_PER_M (14201), UST_M_N_PER_M (9801), UST_M_N_PER_M_SUP_2 (10601), UST_M_PER_K_N (11901), UST_M_PER_S (6101), UST_M_PER_SQ_S (19201), UST_M_SUP_2 (1201), UST_M_SUP_2_PER_K_N (12101), UST_M_SUP_3 (1401), UST_M_SUP_3_PER_K_N (12301), UST_M_SUP_4 (20101), UST_M_SUP_6 (20601), UST_MEGAPASCAL (5001), UST_MI_PER_H (22201), UST_MI_PER_SQ_S (19601), UST_MILLIAMPERE (7101), UST_MILLIVOLT (7401), UST_MIN (21901), UST_MM (201), UST_MM_CARET_2 (2202), UST_MM_CARET_3 (2502), UST_MM_HG (5301), UST_MM_SUP_2 (2201), UST_MM_SUP_3 (2501), UST_MM_SUP_4 (19901), UST_MM_SUP_6 (20401), UST_MS (21701), UST_N (8701), UST_N_DASH_M (11101), UST_N_DASH_M_PER_M (13901), UST_N_PER_M (9501), UST_N_PER_M_SUP_2 (10301), UST_N_PER_MM_SUP_2 (17901), UST_NG_PER_PA_S_SQ_M (22901), UST_NONE (0), UST_OHM_M (23001), UST_ONE_COLON (18201), UST_PA_S (12901), UST_PASCAL (4801), UST_PASCAL_PER_M (3801), UST_PER_MILLE_SIGN (23501), UST_PERCENT_SIGN (1901), UST_POUND (17504), UST_PSF (11001), UST_PSI (5101), UST_PSIA (5104), UST_PSIG (5103), UST_RAD (21401), UST_RAD_PER_S (21601), UST_S (21801), UST_SF (1101), UST_SF_PER_KBTU_PER_H (17702), UST_SF_PER_MBH (17701), UST_SF_PER_TON (17302), UST_SHEQEL (17508), UST_SLOPE_DEGREE_SYMBOL (16001), UST_SQ_CM_PER_M (21001), UST_SQ_FT_PER_FT (20701), UST_SQ_FT_PER_KBTU_PER_H (17704), UST_SQ_FT_PER_MBH (17703), UST_SQ_FT_PER_TON (17301), UST_SQ_IN_PER_FT (20801), UST_SQ_M_K_PER_WATT (18501), UST_SQ_M_PER_KW (17401), UST_SQ_M_PER_M (21101), UST_SQ_MM_PER_M (20901), UST_TF (9301), UST_TF_DASH_M (11701), UST_TF_DASH_M_PER_M (14501), UST_TF_PER_M (10101), UST_TF_PER_M_SUP_2 (10901), UST_THERM (3601), UST_TM (19001), UST_TON (16801), UST_TON_OF_REFRIGERATION (16802), UST_UIN_PER_IN_F (23901), UST_UM_PER_M_C (23801), UST_USGPH (6803), UST_USGPM (6703), UST_USTONNES_FORCE_AS_MASS_ST (24105), UST_USTONNES_FORCE_AS_MASS_T (24104), UST_USTONNES_FORCE_AS_MASS_TONS (24103), UST_USTONNES_FORCE_STF (24102), UST_USTONNES_FORCE_TONSF (24101), UST_USTONNES_MASS_ST (24003), UST_USTONNES_MASS_T (24002), UST_USTONNES_MASS_TONS (24001), UST_VOLT (7201), UST_VOLTAMPERE (8401), UST_WATT (3901), UST_WATT_PER_CU_FT (16401), UST_WATT_PER_CU_M (16501), UST_WATT_PER_SQ_FT (4501), UST_WATT_PER_SQ_M (4601), UST_WATT_PER_SQ_M_K (15401), UST_WATTS_PER_METER_KELVIN (22601), UST_WON (17507), UST_YEN (17505)
    """
    def __eq__(self, *args): #cannot find CLR method
        """ x.__eq__(y) <==> x==yx.__eq__(y) <==> x==yx.__eq__(y) <==> x==y """
        pass

    def __format__(self, *args): #cannot find CLR method
        """ __format__(formattable: IFormattable, format: str) -> str """
        pass

    def __ge__(self, *args): #cannot find CLR method
        pass

    def __gt__(self, *args): #cannot find CLR method
        pass

    def __init__(self, *args): #cannot find CLR method
        """ x.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signature """
        pass

    def __le__(self, *args): #cannot find CLR method
        pass

    def __lt__(self, *args): #cannot find CLR method
        pass

    def __ne__(self, *args): #cannot find CLR method
        pass

    def __reduce_ex__(self, *args): #cannot find CLR method
        pass

    def __str__(self, *args): #cannot find CLR method
        pass

    UST_ACRES = None
    UST_AMPERE = None
    UST_ATM = None
    UST_BAHT = None
    UST_BAR = None
    UST_BTU = None
    UST_BTU_PER_F = None
    UST_BTU_PER_H = None
    UST_BTU_PER_H_CU_FT = None
    UST_BTU_PER_H_FT_DEGREE_F = None
    UST_BTU_PER_H_SQ_FT = None
    UST_BTU_PER_H_SQ_FT_DEGREE_F = None
    UST_BTU_PER_LB = None
    UST_BTU_PER_LB_DEGREE_F = None
    UST_BTU_PER_S = None
    UST_CAL = None
    UST_CAL_PER_S = None
    UST_CD = None
    UST_CD_PER_SQ_M = None
    UST_CF = None
    UST_CFM = None
    UST_CFM_PER_CF = None
    UST_CFM_PER_CU_FT = None
    UST_CFM_PER_SF = None
    UST_CFM_PER_SQ_FT = None
    UST_CFM_PER_TON = None
    UST_CHINESE_HONG_KONG_SAR = None
    UST_CM = None
    UST_CMH = None
    UST_CMS = None
    UST_CM_CARET_2 = None
    UST_CM_CARET_3 = None
    UST_CM_PER_MIN = None
    UST_CM_SUP_2 = None
    UST_CM_SUP_3 = None
    UST_CM_SUP_4 = None
    UST_CM_SUP_6 = None
    UST_COLON_10 = None
    UST_COLON_12 = None
    UST_CP = None
    UST_CPS = None
    UST_CU_FT_PER_MIN = None
    UST_CU_M_PER_H = None
    UST_CU_M_PER_S = None
    UST_CY = None
    UST_DA_N = None
    UST_DA_N_DASH_M = None
    UST_DA_N_DASH_M_PER_M = None
    UST_DA_N_PER_M = None
    UST_DA_N_PER_M_SUP_2 = None
    UST_DEGREE_C = None
    UST_DEGREE_C_DIFFERENCE = None
    UST_DEGREE_F = None
    UST_DEGREE_F_DIFFERENCE = None
    UST_DEGREE_R = None
    UST_DEGREE_R_DIFFERENCE = None
    UST_DEGREE_SYMBOL = None
    UST_DELTA_DEGREE_C = None
    UST_DELTA_DEGREE_F = None
    UST_DELTA_DEGREE_R = None
    UST_DELTA_KELVIN = None
    UST_DM = None
    UST_DOLLAR = None
    UST_DONG = None
    UST_EURO_PREFIX = None
    UST_EURO_SUFFIX = None
    UST_FC = None
    UST_FEET_OF_WATER = None
    UST_FEET_OF_WATER_PER_100FT = None
    UST_FL = None
    UST_FL_LOWERCASE = None
    UST_FOOT_SINGLE_QUOTE = None
    UST_FPM = None
    UST_FPS = None
    UST_FT = None
    UST_FTC = None
    UST_FTH2O = None
    UST_FTH2O_PER_100FT = None
    UST_FTL = None
    UST_FT_CARET_2 = None
    UST_FT_CARET_3 = None
    UST_FT_OF_WATER = None
    UST_FT_OF_WATER_PER_100FT = None
    UST_FT_PER_KIP = None
    UST_FT_PER_MIN = None
    UST_FT_PER_S = None
    UST_FT_PER_SQ_S = None
    UST_FT_SUP_2 = None
    UST_FT_SUP_2_PER_KIP = None
    UST_FT_SUP_3 = None
    UST_FT_SUP_3_PER_KIP = None
    UST_FT_SUP_4 = None
    UST_FT_SUP_6 = None
    UST_GAL = None
    UST_GAL_PER_H = None
    UST_GAL_PER_MIN = None
    UST_GPH = None
    UST_GPM = None
    UST_GRAD = None
    UST_GR_PER_H_SQ_FT_IN_HG = None
    UST_H = None
    UST_HECTARES = None
    UST_HP = None
    UST_HZ = None
    UST_H_SQ_FT_DEGREE_F_PER_BTU = None
    UST_IN = None
    UST_INCH_DOUBLE_QUOTE = None
    UST_INV_DEGREE_C = None
    UST_INV_DEGREE_F = None
    UST_INV_KIP = None
    UST_INV_K_N = None
    UST_IN_CARET_2 = None
    UST_IN_CARET_3 = None
    UST_IN_HG = None
    UST_IN_PER_SQ_S = None
    UST_IN_SUP_2 = None
    UST_IN_SUP_3 = None
    UST_IN_SUP_4 = None
    UST_IN_SUP_6 = None
    UST_IN_WG = None
    UST_IN_WG_PER_100FT = None
    UST_JOULE = None
    UST_J_PER_G = None
    UST_J_PER_G_CELSIUS = None
    UST_J_PER_KELVIN = None
    UST_J_PER_KG_CELSIUS = None
    UST_KCAL = None
    UST_KCAL_PER_S = None
    UST_KELVIN = None
    UST_KELVIN_DIFFERENCE = None
    UST_KGF = None
    UST_KGF_DASH_M = None
    UST_KGF_DASH_M_PER_M = None
    UST_KGF_PER_M = None
    UST_KGF_PER_M_SUP_2 = None
    UST_KGM = None
    UST_KGM_PER_M = None
    UST_KGM_PER_SQ_M = None
    UST_KG_PER_CU_M = None
    UST_KILOAMPERE = None
    UST_KILOPASCAL = None
    UST_KILOVOLT = None
    UST_KILOVOLTAMPERE = None
    UST_KILOWATT = None
    UST_KIP = None
    UST_KIPS_PER_CU_FT = None
    UST_KIPS_PER_IN = None
    UST_KIP_DASH_FT = None
    UST_KIP_DASH_FT_PER_FT = None
    UST_KIP_FT_PER_DEGREE = None
    UST_KIP_FT_PER_DEGREE_PER_FT = None
    UST_KIP_PER_FT = None
    UST_KIP_PER_IN_SUP_3 = None
    UST_KIP_PER_SQ_FT = None
    UST_KIP_PER_SQ_IN = None
    UST_KJ = None
    UST_KJ_PER_KELVIN = None
    UST_KM_PER_H = None
    UST_KM_PER_SQ_S = None
    UST_KN_PER_M_SUP_3 = None
    UST_KRONER = None
    UST_KSF = None
    UST_KSI = None
    UST_KWH = None
    UST_K_N = None
    UST_K_N_DASH_M = None
    UST_K_N_DASH_M_PER_M = None
    UST_K_N_M_PER_DEGREE = None
    UST_K_N_M_PER_DEGREE_PER_M = None
    UST_K_N_PER_CM_SUP_2 = None
    UST_K_N_PER_M = None
    UST_K_N_PER_MM_SUP_2 = None
    UST_K_N_PER_M_SUP_2 = None
    UST_L = None
    UST_LBF = None
    UST_LBF_DASH_FT = None
    UST_LBF_DASH_FT_PER_FT = None
    UST_LBF_PER_CU_FT = None
    UST_LBF_PER_FT = None
    UST_LBF_PER_SQ_FT = None
    UST_LBF_PER_SQ_IN = None
    UST_LBM = None
    UST_LBM_PER_CU_FT = None
    UST_LBM_PER_CU_IN = None
    UST_LBM_PER_FT = None
    UST_LBM_PER_FT_H = None
    UST_LBM_PER_FT_S = None
    UST_LBM_PER_SQ_FT = None
    UST_LB_FORCE = None
    UST_LB_FORCE_DASH_FT = None
    UST_LB_FORCE_DASH_FT_PER_FT = None
    UST_LB_FORCE_PER_CU_FT = None
    UST_LB_FORCE_PER_FT = None
    UST_LB_FORCE_PER_FT_H = None
    UST_LB_FORCE_PER_FT_S = None
    UST_LB_FORCE_PER_SQ_FT = None
    UST_LB_FORCE_PER_SQ_IN = None
    UST_LB_MASS = None
    UST_LB_MASS_PER_CU_FT = None
    UST_LB_MASS_PER_CU_IN = None
    UST_LB_MASS_PER_FT = None
    UST_LF = None
    UST_LM = None
    UST_LM_PER_W = None
    UST_LPM = None
    UST_LPS = None
    UST_LPS_PER_SQ_M = None
    UST_LX = None
    UST_L_PER_M = None
    UST_L_PER_S = None
    UST_L_PER_S_CU_M = None
    UST_L_PER_S_KW = None
    UST_L_PER_S_SQ_M = None
    UST_M = None
    UST_MEGAPASCAL = None
    UST_MILLIAMPERE = None
    UST_MILLIVOLT = None
    UST_MIN = None
    UST_MI_PER_H = None
    UST_MI_PER_SQ_S = None
    UST_MM = None
    UST_MM_CARET_2 = None
    UST_MM_CARET_3 = None
    UST_MM_HG = None
    UST_MM_SUP_2 = None
    UST_MM_SUP_3 = None
    UST_MM_SUP_4 = None
    UST_MM_SUP_6 = None
    UST_MS = None
    UST_M_CARET_2 = None
    UST_M_CARET_3 = None
    UST_M_N = None
    UST_M_N_DASH_M = None
    UST_M_N_DASH_M_PER_M = None
    UST_M_N_PER_M = None
    UST_M_N_PER_M_SUP_2 = None
    UST_M_PER_K_N = None
    UST_M_PER_S = None
    UST_M_PER_SQ_S = None
    UST_M_SUP_2 = None
    UST_M_SUP_2_PER_K_N = None
    UST_M_SUP_3 = None
    UST_M_SUP_3_PER_K_N = None
    UST_M_SUP_4 = None
    UST_M_SUP_6 = None
    UST_N = None
    UST_NG_PER_PA_S_SQ_M = None
    UST_NONE = None
    UST_N_DASH_M = None
    UST_N_DASH_M_PER_M = None
    UST_N_PER_M = None
    UST_N_PER_MM_SUP_2 = None
    UST_N_PER_M_SUP_2 = None
    UST_OHM_M = None
    UST_ONE_COLON = None
    UST_PASCAL = None
    UST_PASCAL_PER_M = None
    UST_PA_S = None
    UST_PERCENT_SIGN = None
    UST_PER_MILLE_SIGN = None
    UST_POUND = None
    UST_PSF = None
    UST_PSI = None
    UST_PSIA = None
    UST_PSIG = None
    UST_RAD = None
    UST_RAD_PER_S = None
    UST_S = None
    UST_SF = None
    UST_SF_PER_KBTU_PER_H = None
    UST_SF_PER_MBH = None
    UST_SF_PER_TON = None
    UST_SHEQEL = None
    UST_SLOPE_DEGREE_SYMBOL = None
    UST_SQ_CM_PER_M = None
    UST_SQ_FT_PER_FT = None
    UST_SQ_FT_PER_KBTU_PER_H = None
    UST_SQ_FT_PER_MBH = None
    UST_SQ_FT_PER_TON = None
    UST_SQ_IN_PER_FT = None
    UST_SQ_MM_PER_M = None
    UST_SQ_M_K_PER_WATT = None
    UST_SQ_M_PER_KW = None
    UST_SQ_M_PER_M = None
    UST_TF = None
    UST_TF_DASH_M = None
    UST_TF_DASH_M_PER_M = None
    UST_TF_PER_M = None
    UST_TF_PER_M_SUP_2 = None
    UST_THERM = None
    UST_TM = None
    UST_TON = None
    UST_TON_OF_REFRIGERATION = None
    UST_UIN_PER_IN_F = None
    UST_UM_PER_M_C = None
    UST_USGPH = None
    UST_USGPM = None
    UST_USTONNES_FORCE_AS_MASS_ST = None
    UST_USTONNES_FORCE_AS_MASS_T = None
    UST_USTONNES_FORCE_AS_MASS_TONS = None
    UST_USTONNES_FORCE_STF = None
    UST_USTONNES_FORCE_TONSF = None
    UST_USTONNES_MASS_ST = None
    UST_USTONNES_MASS_T = None
    UST_USTONNES_MASS_TONS = None
    UST_VOLT = None
    UST_VOLTAMPERE = None
    UST_WATT = None
    UST_WATTS_PER_METER_KELVIN = None
    UST_WATT_PER_CU_FT = None
    UST_WATT_PER_CU_M = None
    UST_WATT_PER_SQ_FT = None
    UST_WATT_PER_SQ_M = None
    UST_WATT_PER_SQ_M_K = None
    UST_WON = None
    UST_YEN = None
    value__ = None

