# encoding: utf-8
# module Grasshopper.GUI.SettingsControls calls itself SettingsControls
# from Grasshopper,Version=1.0.0.20,Culture=neutral,PublicKeyToken=dda4f5ec2cd80803
# by generator 1.145
""" NamespaceTracker represent a CLS namespace. """
# no imports

# no functions
# classes
from SettingsControls_parts.GH_AlignWidgetFrontEnd import GH_AlignWidgetFrontEnd
from SettingsControls_parts.GH_AuthorSettings_FrontEnd import GH_AuthorSettings_FrontEnd
from SettingsControls_parts.GH_AutoSaveSettingsFrontEnd import GH_AutoSaveSettingsFrontEnd
from SettingsControls_parts.GH_CanvasOverlaySettingsFrontEnd import GH_CanvasOverlaySettingsFrontEnd
from SettingsControls_parts.GH_CanvasSettings_FrontEnd import GH_CanvasSettings_FrontEnd
from SettingsControls_parts.GH_CompassWidgetFrontEnd import GH_CompassWidgetFrontEnd
from SettingsControls_parts.GH_DefaultPreviewColourSettingsFrontEnd import GH_DefaultPreviewColourSettingsFrontEnd
from SettingsControls_parts.GH_DocumentPreviewColourSettingsFrontEnd import GH_DocumentPreviewColourSettingsFrontEnd
from SettingsControls_parts.GH_FontFamilySettingsFrontEnd import GH_FontFamilySettingsFrontEnd
from SettingsControls_parts.GH_GenericCapsulePaletteSettings import GH_GenericCapsulePaletteSettings
from SettingsControls_parts.GH_GHALoadingOptionsFrontEnd import GH_GHALoadingOptionsFrontEnd
from SettingsControls_parts.GH_MarkovWidgetSettingFrontEnd import GH_MarkovWidgetSettingFrontEnd
from SettingsControls_parts.GH_MenuShortcutFrontEnd import GH_MenuShortcutFrontEnd
from SettingsControls_parts.GH_MessageWidgetFrontEnd import GH_MessageWidgetFrontEnd
from SettingsControls_parts.GH_NumberFormattingSettingsFrontEnd import GH_NumberFormattingSettingsFrontEnd
from SettingsControls_parts.GH_ObjectMenuSettingsFrontEnd import GH_ObjectMenuSettingsFrontEnd
from SettingsControls_parts.GH_PreviewSettingsFrontEnd import GH_PreviewSettingsFrontEnd
from SettingsControls_parts.GH_ProfilerWidgetFrontEnd import GH_ProfilerWidgetFrontEnd
from SettingsControls_parts.GH_PruderySettingsFrontEnd import GH_PruderySettingsFrontEnd
from SettingsControls_parts.GH_RecentFilesSettingsFrontEnd import GH_RecentFilesSettingsFrontEnd
from SettingsControls_parts.GH_RibbonSettingsFrontEnd import GH_RibbonSettingsFrontEnd
from SettingsControls_parts.GH_SolverSettings_FrontEnd import GH_SolverSettings_FrontEnd
from SettingsControls_parts.GH_TemplateFileSettings import GH_TemplateFileSettings
from SettingsControls_parts.GH_TooltipSettings_FrontEnd import GH_TooltipSettings_FrontEnd
from SettingsControls_parts.GH_ZuiZoomFrontEnd import GH_ZuiZoomFrontEnd
