class ConnectionValidationInfo(object, IDisposable):
    """
    This object contains information about fabrication connection validations.
    
    ConnectionValidationInfo()
    """
    def Dispose(self):
        """ Dispose(self: ConnectionValidationInfo) """
        pass

    def GetWarning(self, index):
        """
        GetWarning(self: ConnectionValidationInfo, index: int) -> ConnectionValidationWarning
        
            Access specific warning number of warnings generated by reload.
        """
        pass

    def IsValidWarningIndex(self, index):
        """
        IsValidWarningIndex(self: ConnectionValidationInfo, index: int) -> bool
        
            Validate warning index.
        """
        pass

    def ManyWarnings(self):
        """
        ManyWarnings(self: ConnectionValidationInfo) -> int
        
            Returns number of warnings generated by reload.
        """
        pass

    def ReleaseUnmanagedResources(self, *args): #cannot find CLR method
        """ ReleaseUnmanagedResources(self: ConnectionValidationInfo, disposing: bool) """
        pass

    def __enter__(self, *args): #cannot find CLR method
        """ __enter__(self: IDisposable) -> object """
        pass

    def __exit__(self, *args): #cannot find CLR method
        """ __exit__(self: IDisposable, exc_type: object, exc_value: object, exc_back: object) """
        pass

    def __init__(self, *args): #cannot find CLR method
        """ x.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signature """
        pass

    def __repr__(self, *args): #cannot find CLR method
        """ __repr__(self: object) -> str """
        pass

    IsValidObject = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """Specifies whether the .NET object represents a valid Revit entity.

Get: IsValidObject(self: ConnectionValidationInfo) -> bool

"""


