class ImageType(ElementType, IDisposable):
    """ Represents a type containing an image. Instances of this type can be displayed in 2D views, sheets, and schedules. """
    @staticmethod
    def Create(document, imagePath):
        """
        Create(document: Document, imagePath: str) -> ImageType
        
            Creates a new ImageType element and loads the image into it.
        
            document: The document.
            imagePath: A path to an image file to load.
            Returns: The new ImageType.
        """
        pass

    def Dispose(self):
        """ Dispose(self: Element, A_0: bool) """
        pass

    def getBoundingBox(self, *args): #cannot find CLR method
        """ getBoundingBox(self: Element, view: View) -> BoundingBoxXYZ """
        pass

    def GetImage(self):
        """
        GetImage(self: ImageType) -> Bitmap
        
            Get the bitmap image stored in the image symbol.
            Returns: The bitmap image at the original loaded image size.
        """
        pass

    def IsLoadedFromFile(self):
        """
        IsLoadedFromFile(self: ImageType) -> bool
        
            Checks whether the image is loaded from a file.
           Revit may generate some 
             images internally, such as the images created by "Save to Project as Image".
        
            Returns: True if the image is loaded from a file, False otherwise.
        """
        pass

    def ReleaseUnmanagedResources(self, *args): #cannot find CLR method
        """ ReleaseUnmanagedResources(self: Element, disposing: bool) """
        pass

    def Reload(self):
        """
        Reload(self: ImageType)
            Reloads the image from its origin file.
        """
        pass

    def ReloadFrom(self, imagePath):
        """
        ReloadFrom(self: ImageType, imagePath: str)
            Reloads the image from new image file.
        
            imagePath: A new path to an image file to load.
        """
        pass

    def setElementType(self, *args): #cannot find CLR method
        """ setElementType(self: Element, type: ElementType, incompatibleExceptionMessage: str) """
        pass

    def __enter__(self, *args): #cannot find CLR method
        """ __enter__(self: IDisposable) -> object """
        pass

    def __exit__(self, *args): #cannot find CLR method
        """ __exit__(self: IDisposable, exc_type: object, exc_value: object, exc_back: object) """
        pass

    def __init__(self, *args): #cannot find CLR method
        """ x.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signature """
        pass

    Path = property(lambda self: object(), lambda self, v: None, lambda self: None)  # default
    """The original image file path used if the image is loaded from a disk file, or empty if the image
   is generated by Revit internally, such as the images created by "Save to Project as Image".

Get: Path(self: ImageType) -> str

"""


