class BuiltInFailures(object):
 """ Provides a container of all Revit built-in FailureDefinitionId instances. """
 AnalyticalModelFailures=None
 ArrayFailures=None
 AssemblyFailures=None
 AutoJoinFailures=None
 AutoRouteFailures=None
 BeamFailures=None
 BeamSystemFailures=None
 BendFailures=None
 BlendFailures=None
 ColorFillFailures=None
 ColumnFailures=None
 ColumnInsideWallFailures=None
 ComponentRepeaterFailures=None
 ComponentRepeaterSlotFailures=None
 ConnectorFailures=None
 ConstraintFailures=None
 ConversionFailures=None
 CopyMonitorFailures=None
 CopyPasteFailures=None
 CreationFailures=None
 CurtainGridFamilyFailures=None
 CurtainWallFailures=None
 CurveByPointFailures=None
 CurveFailures=None
 CutFailures=None
 CutterFailures=None
 CuttingFailures=None
 DatumPlaneFailures=None
 DebugTabBindingFailures=None
 DecalFailures=None
 DesignOptionFailures=None
 DetailFailures=None
 DimensionFailures=None
 DisplacementElementFailures=None
 DividedPathFailures=None
 DividedSurfaceFailures=None
 DocumentFailures=None
 DPartFailures=None
 DuctFailures=None
 EditingFailures=None
 ElectricalFailures=None
 ElectricityFailures=None
 ElementFailures=None
 ElementTypeFailures=None
 ElevationFailures=None
 EnergyAnalysisFailures=None
 EnergyAnalysisUtilitiesDBFailures=None
 ExportFailures=None
 ExtrusionFailures=None
 FabricAreaFailures=None
 FabricationShapeFailures=None
 FabricFailures=None
 FabricSheetFailures=None
 FaceSplitterFailures=None
 FamilyFailures=None
 FilledRegionFailures=None
 FloorFailures=None
 FluidFailures=None
 FormFailures=None
 GeneralFailures=None
 GenericFailures=None
 GenericMEPFailures=None
 GeometryFailures=None
 GlobalParameterFailures=None
 GridChainSketchFailures=None
 GridFailures=None
 GroupFailures=None
 HostObjFailures=None
 HvacFailures=None
 IlluminationFailures=None
 ImageFailures=None
 ImportExportFailures=None
 ImportFailures=None
 InaccurateFailures=None
 InfillFailures=None
 InterferenceFailures=None
 JoinElementsFailures=None
 KeyBasedTreeEntryFailures=None
 KeyBasedTreeFileFailures=None
 KeynoteFailures=None
 KeynoteTagFailures=None
 LegendFailures=None
 LevelFailures=None
 LinkFailures=None
 LoadFailures=None
 LooseDimensionFailures=None
 MassFailures=None
 MatchlineFailures=None
 MechanicalFailures=None
 MEPCalculationFailures=None
 MEPFabricationFailures=None
 MirrorFailures=None
 MultiReferenceAnnotationFailures=None
 NumberingFailures=None
 OffsetFacesCellLegacyFailures=None
 OpeningFailures=None
 OverlapFailures=None
 ParameterFailures=None
 PartMakerMethodForFamilyInstanceFailures=None
 PartMakerMethodForMergePartFailures=None
 PartMakerMethodForWallFailures=None
 PathFailures=None
 PerformanceFailures=None
 PipingFailures=None
 PlanRegionFailures=None
 PointFailures=None
 ProfileFailures=None
 PropertySetElementFailures=None
 RebarCouplerFailures=None
 RebarFailures=None
 RebarShapeFailures=None
 RebarSystemFailures=None
 RefPlaneFailures=None
 RegenFailures=None
 RenderFailures=None
 RevisionCloudFailures=None
 RevisionFailures=None
 RevolutionFailures=None
 RoofFailures=None
 RoomFailures=None
 ScheduleViewFailures=None
 SculptingFailures=None
 SectionViewFailures=None
 SelectionFailures=None
 SheetFailures=None
 SiteFailures=None
 SiteImportFailures=None
 SketchFailures=None
 SkylightFailures=None
 SlabFailures=None
 SlabShapeFailures=None
 SlantedColumnFailures=None
 SpanDirectionSymbolFailures=None
 SplineFailures=None
 StairRampFailures=None
 StructuralAssetFailures=None
 StructuralConnectionFailures=None
 StructuralLoadFailures=None
 SweepFailures=None
 SweptBlendFailures=None
 SystemNavigatorFailures=None
 SystemsFailures=None
 TagFailures=None
 TextFailures=None
 TilePatternTileFailures=None
 ToggleViewFailures=None
 TrussFailures=None
 UniqueElementFailures=None
 ViewFailures=None
 WallFailures=None
 WallJoinFailures=None
 WallJoinRoofFailures=None
 WorksharingFailures=None
 __all__=[
  'AnalyticalModelFailures',
  'ArrayFailures',
  'AssemblyFailures',
  'AutoJoinFailures',
  'AutoRouteFailures',
  'BeamFailures',
  'BeamSystemFailures',
  'BendFailures',
  'BlendFailures',
  'ColorFillFailures',
  'ColumnFailures',
  'ColumnInsideWallFailures',
  'ComponentRepeaterFailures',
  'ComponentRepeaterSlotFailures',
  'ConnectorFailures',
  'ConstraintFailures',
  'ConversionFailures',
  'CopyMonitorFailures',
  'CopyPasteFailures',
  'CreationFailures',
  'CurtainGridFamilyFailures',
  'CurtainWallFailures',
  'CurveByPointFailures',
  'CurveFailures',
  'CutFailures',
  'CutterFailures',
  'CuttingFailures',
  'DatumPlaneFailures',
  'DebugTabBindingFailures',
  'DecalFailures',
  'DesignOptionFailures',
  'DetailFailures',
  'DimensionFailures',
  'DisplacementElementFailures',
  'DividedPathFailures',
  'DividedSurfaceFailures',
  'DocumentFailures',
  'DPartFailures',
  'DuctFailures',
  'EditingFailures',
  'ElectricalFailures',
  'ElectricityFailures',
  'ElementFailures',
  'ElementTypeFailures',
  'ElevationFailures',
  'EnergyAnalysisFailures',
  'EnergyAnalysisUtilitiesDBFailures',
  'ExportFailures',
  'ExtrusionFailures',
  'FabricAreaFailures',
  'FabricationShapeFailures',
  'FabricFailures',
  'FabricSheetFailures',
  'FaceSplitterFailures',
  'FamilyFailures',
  'FilledRegionFailures',
  'FloorFailures',
  'FluidFailures',
  'FormFailures',
  'GeneralFailures',
  'GenericFailures',
  'GenericMEPFailures',
  'GeometryFailures',
  'GlobalParameterFailures',
  'GridChainSketchFailures',
  'GridFailures',
  'GroupFailures',
  'HostObjFailures',
  'HvacFailures',
  'IlluminationFailures',
  'ImageFailures',
  'ImportExportFailures',
  'ImportFailures',
  'InaccurateFailures',
  'InfillFailures',
  'InterferenceFailures',
  'JoinElementsFailures',
  'KeyBasedTreeEntryFailures',
  'KeyBasedTreeFileFailures',
  'KeynoteFailures',
  'KeynoteTagFailures',
  'LegendFailures',
  'LevelFailures',
  'LinkFailures',
  'LoadFailures',
  'LooseDimensionFailures',
  'MassFailures',
  'MatchlineFailures',
  'MechanicalFailures',
  'MEPCalculationFailures',
  'MEPFabricationFailures',
  'MirrorFailures',
  'MultiReferenceAnnotationFailures',
  'NumberingFailures',
  'OffsetFacesCellLegacyFailures',
  'OpeningFailures',
  'OverlapFailures',
  'ParameterFailures',
  'PartMakerMethodForFamilyInstanceFailures',
  'PartMakerMethodForMergePartFailures',
  'PartMakerMethodForWallFailures',
  'PathFailures',
  'PerformanceFailures',
  'PipingFailures',
  'PlanRegionFailures',
  'PointFailures',
  'ProfileFailures',
  'PropertySetElementFailures',
  'RebarCouplerFailures',
  'RebarFailures',
  'RebarShapeFailures',
  'RebarSystemFailures',
  'RefPlaneFailures',
  'RegenFailures',
  'RenderFailures',
  'RevisionCloudFailures',
  'RevisionFailures',
  'RevolutionFailures',
  'RoofFailures',
  'RoomFailures',
  'ScheduleViewFailures',
  'SculptingFailures',
  'SectionViewFailures',
  'SelectionFailures',
  'SheetFailures',
  'SiteFailures',
  'SiteImportFailures',
  'SketchFailures',
  'SkylightFailures',
  'SlabFailures',
  'SlabShapeFailures',
  'SlantedColumnFailures',
  'SpanDirectionSymbolFailures',
  'SplineFailures',
  'StairRampFailures',
  'StructuralAssetFailures',
  'StructuralConnectionFailures',
  'StructuralLoadFailures',
  'SweepFailures',
  'SweptBlendFailures',
  'SystemNavigatorFailures',
  'SystemsFailures',
  'TagFailures',
  'TextFailures',
  'TilePatternTileFailures',
  'ToggleViewFailures',
  'TrussFailures',
  'UniqueElementFailures',
  'ViewFailures',
  'WallFailures',
  'WallJoinFailures',
  'WallJoinRoofFailures',
  'WorksharingFailures',
 ]

