# encoding: utf-8
# module System.Windows.Media calls itself Media
# from PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
# by generator 1.145
""" NamespaceTracker represent a CLS namespace. """
# no imports

# no functions
# classes
from __init___parts.HitTestResult import HitTestResult
from __init___parts.PointHitTestResult import PointHitTestResult
from __init___parts.AdornerHitTestResult import AdornerHitTestResult
from __init___parts.AlignmentX import AlignmentX
from __init___parts.AlignmentY import AlignmentY
from __init___parts.PathSegment import PathSegment
from __init___parts.ArcSegment import ArcSegment
from __init___parts.BezierSegment import BezierSegment
from __init___parts.CacheMode import CacheMode
from __init___parts.BitmapCache import BitmapCache
from __init___parts.Brush import Brush
from __init___parts.BitmapCacheBrush import BitmapCacheBrush
from __init___parts.BitmapScalingMode import BitmapScalingMode
from __init___parts.BrushConverter import BrushConverter
from __init___parts.Brushes import Brushes
from __init___parts.BrushMappingMode import BrushMappingMode
from __init___parts.CacheModeConverter import CacheModeConverter
from __init___parts.CachingHint import CachingHint
from __init___parts.CharacterMetrics import CharacterMetrics
from __init___parts.CharacterMetricsDictionary import CharacterMetricsDictionary
from __init___parts.ClearTypeHint import ClearTypeHint
from __init___parts.Color import Color
from __init___parts.ColorContext import ColorContext
from __init___parts.ColorConverter import ColorConverter
from __init___parts.ColorInterpolationMode import ColorInterpolationMode
from __init___parts.Colors import Colors
from __init___parts.Geometry import Geometry
from __init___parts.CombinedGeometry import CombinedGeometry
from __init___parts.CompositionTarget import CompositionTarget
from __init___parts.Visual import Visual
from __init___parts.ContainerVisual import ContainerVisual
from __init___parts.DashStyle import DashStyle
from __init___parts.DashStyles import DashStyles
from __init___parts.DisableDpiAwarenessAttribute import DisableDpiAwarenessAttribute
from __init___parts.DoubleCollection import DoubleCollection
from __init___parts.DoubleCollectionConverter import DoubleCollectionConverter
from __init___parts.Drawing import Drawing
from __init___parts.TileBrush import TileBrush
from __init___parts.DrawingBrush import DrawingBrush
from __init___parts.DrawingCollection import DrawingCollection
from __init___parts.DrawingContext import DrawingContext
from __init___parts.DrawingGroup import DrawingGroup
from __init___parts.ImageSource import ImageSource
from __init___parts.DrawingImage import DrawingImage
from __init___parts.DrawingVisual import DrawingVisual
from __init___parts.EdgeMode import EdgeMode
from __init___parts.EllipseGeometry import EllipseGeometry
from __init___parts.ExceptionEventArgs import ExceptionEventArgs
from __init___parts.FamilyTypeface import FamilyTypeface
from __init___parts.FamilyTypefaceCollection import FamilyTypefaceCollection
from __init___parts.FillRule import FillRule
from __init___parts.FontEmbeddingManager import FontEmbeddingManager
from __init___parts.FontEmbeddingRight import FontEmbeddingRight
from __init___parts.FontFamily import FontFamily
from __init___parts.FontFamilyConverter import FontFamilyConverter
from __init___parts.FontFamilyMap import FontFamilyMap
from __init___parts.FontFamilyMapCollection import FontFamilyMapCollection
from __init___parts.FontFamilyValueSerializer import FontFamilyValueSerializer
from __init___parts.Fonts import Fonts
from __init___parts.FormattedText import FormattedText
from __init___parts.GeneralTransform import GeneralTransform
from __init___parts.GeneralTransformCollection import GeneralTransformCollection
from __init___parts.GeneralTransformGroup import GeneralTransformGroup
from __init___parts.GeometryCollection import GeometryCollection
from __init___parts.GeometryCombineMode import GeometryCombineMode
from __init___parts.GeometryConverter import GeometryConverter
from __init___parts.GeometryDrawing import GeometryDrawing
from __init___parts.GeometryGroup import GeometryGroup
from __init___parts.HitTestParameters import HitTestParameters
from __init___parts.GeometryHitTestParameters import GeometryHitTestParameters
from __init___parts.GeometryHitTestResult import GeometryHitTestResult
from __init___parts.GlyphRun import GlyphRun
from __init___parts.GlyphRunDrawing import GlyphRunDrawing
from __init___parts.GlyphTypeface import GlyphTypeface
from __init___parts.GradientBrush import GradientBrush
from __init___parts.GradientSpreadMethod import GradientSpreadMethod
from __init___parts.GradientStop import GradientStop
from __init___parts.GradientStopCollection import GradientStopCollection
from __init___parts.GuidelineSet import GuidelineSet
from __init___parts.HitTestFilterBehavior import HitTestFilterBehavior
from __init___parts.HitTestFilterCallback import HitTestFilterCallback
from __init___parts.HitTestResultBehavior import HitTestResultBehavior
from __init___parts.HitTestResultCallback import HitTestResultCallback
from __init___parts.HostVisual import HostVisual
from __init___parts.ImageBrush import ImageBrush
from __init___parts.ImageDrawing import ImageDrawing
from __init___parts.ImageMetadata import ImageMetadata
from __init___parts.ImageSourceConverter import ImageSourceConverter
from __init___parts.ImageSourceValueSerializer import ImageSourceValueSerializer
from __init___parts.Int32Collection import Int32Collection
from __init___parts.Int32CollectionConverter import Int32CollectionConverter
from __init___parts.IntersectionDetail import IntersectionDetail
from __init___parts.InvalidWmpVersionException import InvalidWmpVersionException
from __init___parts.LanguageSpecificStringDictionary import LanguageSpecificStringDictionary
from __init___parts.LinearGradientBrush import LinearGradientBrush
from __init___parts.LineGeometry import LineGeometry
from __init___parts.LineSegment import LineSegment
from __init___parts.Matrix import Matrix
from __init___parts.MatrixConverter import MatrixConverter
from __init___parts.Transform import Transform
from __init___parts.MatrixTransform import MatrixTransform
from __init___parts.MediaClock import MediaClock
from __init___parts.MediaPlayer import MediaPlayer
from __init___parts.MediaScriptCommandEventArgs import MediaScriptCommandEventArgs
from __init___parts.MediaTimeline import MediaTimeline
from __init___parts.NumberCultureSource import NumberCultureSource
from __init___parts.NumberSubstitution import NumberSubstitution
from __init___parts.NumberSubstitutionMethod import NumberSubstitutionMethod
from __init___parts.PathFigure import PathFigure
from __init___parts.PathFigureCollection import PathFigureCollection
from __init___parts.PathFigureCollectionConverter import PathFigureCollectionConverter
from __init___parts.PathGeometry import PathGeometry
from __init___parts.PathSegmentCollection import PathSegmentCollection
from __init___parts.Pen import Pen
from __init___parts.PenLineCap import PenLineCap
from __init___parts.PenLineJoin import PenLineJoin
from __init___parts.PixelFormat import PixelFormat
from __init___parts.PixelFormatChannelMask import PixelFormatChannelMask
from __init___parts.PixelFormatConverter import PixelFormatConverter
from __init___parts.PixelFormats import PixelFormats
from __init___parts.PointCollection import PointCollection
from __init___parts.PointCollectionConverter import PointCollectionConverter
from __init___parts.PointHitTestParameters import PointHitTestParameters
from __init___parts.PolyBezierSegment import PolyBezierSegment
from __init___parts.PolyLineSegment import PolyLineSegment
from __init___parts.PolyQuadraticBezierSegment import PolyQuadraticBezierSegment
from __init___parts.QuadraticBezierSegment import QuadraticBezierSegment
from __init___parts.RadialGradientBrush import RadialGradientBrush
from __init___parts.RectangleGeometry import RectangleGeometry
from __init___parts.RenderCapability import RenderCapability
from __init___parts.RenderingEventArgs import RenderingEventArgs
from __init___parts.RenderOptions import RenderOptions
from __init___parts.RequestCachePolicyConverter import RequestCachePolicyConverter
from __init___parts.RotateTransform import RotateTransform
from __init___parts.ScaleTransform import ScaleTransform
from __init___parts.SkewTransform import SkewTransform
from __init___parts.SolidColorBrush import SolidColorBrush
from __init___parts.StreamGeometry import StreamGeometry
from __init___parts.StreamGeometryContext import StreamGeometryContext
from __init___parts.Stretch import Stretch
from __init___parts.StyleSimulations import StyleSimulations
from __init___parts.SweepDirection import SweepDirection
from __init___parts.TextEffect import TextEffect
from __init___parts.TextEffectCollection import TextEffectCollection
from __init___parts.TextFormattingMode import TextFormattingMode
from __init___parts.TextHintingMode import TextHintingMode
from __init___parts.TextOptions import TextOptions
from __init___parts.TextRenderingMode import TextRenderingMode
from __init___parts.TileMode import TileMode
from __init___parts.ToleranceType import ToleranceType
from __init___parts.TransformCollection import TransformCollection
from __init___parts.TransformConverter import TransformConverter
from __init___parts.TransformGroup import TransformGroup
from __init___parts.TranslateTransform import TranslateTransform
from __init___parts.Typeface import Typeface
from __init___parts.VectorCollection import VectorCollection
from __init___parts.VectorCollectionConverter import VectorCollectionConverter
from __init___parts.VideoDrawing import VideoDrawing
from __init___parts.VisualBrush import VisualBrush
from __init___parts.VisualCollection import VisualCollection
from __init___parts.VisualTarget import VisualTarget
from __init___parts.VisualTreeHelper import VisualTreeHelper
