class dotIFC2X3_OwnerHistoryChangeAction_t(Enum):
 """ enum dotIFC2X3_OwnerHistoryChangeAction_t,values: CHANGEACTION_ADDED (2),CHANGEACTION_DELETED (3),CHANGEACTION_MODIFIED (1),CHANGEACTION_NOCHANGE (0) """
 CHANGEACTION_ADDED=None
 CHANGEACTION_DELETED=None
 CHANGEACTION_MODIFIED=None
 CHANGEACTION_NOCHANGE=None
 value__=None

