class dotIFC2X3_OwnerHistoryState_t(Enum):
 """ enum dotIFC2X3_OwnerHistoryState_t,values: STATE_LOCKED (3),STATE_READONLY (2),STATE_READONLYLOCKED (5),STATE_READWRITE (1),STATE_READWRITELOCKED (4),STATE_UNDEFINED (0) """
 STATE_LOCKED=None
 STATE_READONLY=None
 STATE_READONLYLOCKED=None
 STATE_READWRITE=None
 STATE_READWRITELOCKED=None
 STATE_UNDEFINED=None
 value__=None

