class dotTemporaryStatesEnum(Enum):
 """ enum dotTemporaryStatesEnum,values: DOT_TEMPORARY_STATE_ACCEPTED (8),DOT_TEMPORARY_STATE_ACTIVE (6),DOT_TEMPORARY_STATE_DELETED (3),DOT_TEMPORARY_STATE_DM_ONGOING (4),DOT_TEMPORARY_STATE_MODIFIED (2),DOT_TEMPORARY_STATE_NEW (1),DOT_TEMPORARY_STATE_ORIGINAL (7),DOT_TEMPORARY_STATE_REJECTED (9),DOT_TEMPORARY_STATE_UNCHANGED (5),DOT_TEMPORARY_STATE_UNKNOWN (0),DOT_TEMPORARY_STATE_USE_EXISTING_REPRESENTATION (10) """
 DOT_TEMPORARY_STATE_ACCEPTED=None
 DOT_TEMPORARY_STATE_ACTIVE=None
 DOT_TEMPORARY_STATE_DELETED=None
 DOT_TEMPORARY_STATE_DM_ONGOING=None
 DOT_TEMPORARY_STATE_MODIFIED=None
 DOT_TEMPORARY_STATE_NEW=None
 DOT_TEMPORARY_STATE_ORIGINAL=None
 DOT_TEMPORARY_STATE_REJECTED=None
 DOT_TEMPORARY_STATE_UNCHANGED=None
 DOT_TEMPORARY_STATE_UNKNOWN=None
 DOT_TEMPORARY_STATE_USE_EXISTING_REPRESENTATION=None
 value__=None

