class dotTemporaryTransparenciesEnum(Enum):
 """ enum dotTemporaryTransparenciesEnum,values: DOT_TEMPORARY_TRANSPARENCY_HIDDEN (0),DOT_TEMPORARY_TRANSPARENCY_SEMITRANSPARENT (3),DOT_TEMPORARY_TRANSPARENCY_SEMIVISIBLE (5),DOT_TEMPORARY_TRANSPARENCY_TRANSPARENT (1),DOT_TEMPORARY_TRANSPARENCY_VISIBLE (10) """
 DOT_TEMPORARY_TRANSPARENCY_HIDDEN=None
 DOT_TEMPORARY_TRANSPARENCY_SEMITRANSPARENT=None
 DOT_TEMPORARY_TRANSPARENCY_SEMIVISIBLE=None
 DOT_TEMPORARY_TRANSPARENCY_TRANSPARENT=None
 DOT_TEMPORARY_TRANSPARENCY_VISIBLE=None
 value__=None

