class ITypeLibImporterNotifySink:
 """ Provides a callback mechanism for the type library converter to inform the caller of the status of the conversion,and involve the caller in the conversion process itself. """
 def ReportEvent(self,eventKind,eventCode,eventMsg):
  """
  ReportEvent(self: ITypeLibImporterNotifySink,eventKind: ImporterEventKind,eventCode: int,eventMsg: str)

   Notifies the caller that an event occured during the conversion of a type library.

  

   eventKind: An System.Runtime.InteropServices.ImporterEventKind value indicating the type of event.

   eventCode: Indicates extra information about the event.

   eventMsg: A message generated by the event.
  """
  pass
 def ResolveRef(self,typeLib):
  """
  ResolveRef(self: ITypeLibImporterNotifySink,typeLib: object) -> Assembly

  

   Asks the user to resolve a reference to another type library.

  

   typeLib: The object implementing the ITypeLib interface that needs to be resolved.

   Returns: The assembly corresponding to typeLib.
  """
  pass
 def __init__(self,*args):
  """ x.__init__(...) initializes x; see x.__class__.__doc__ for signaturex.__init__(...) initializes x; see x.__class__.__doc__ for signature """
  pass
