# encoding: utf-8
# module Rhino.Geometry calls itself Geometry
# from RhinoCommon,Version=5.1.30000.16,Culture=neutral,PublicKeyToken=552281e97c755530
# by generator 1.145
""" NamespaceTracker represent a CLS namespace. """
# no imports

# no functions
# classes
from __init___parts.GeometryBase import GeometryBase
from __init___parts.AnnotationBase import AnnotationBase
from __init___parts.AngularDimension import AngularDimension
from __init___parts.Arc import Arc
from __init___parts.Curve import Curve
from __init___parts.ArcCurve import ArcCurve
from __init___parts.AreaMassProperties import AreaMassProperties
from __init___parts.BezierCurve import BezierCurve
from __init___parts.BlendContinuity import BlendContinuity
from __init___parts.BoundingBox import BoundingBox
from __init___parts.Box import Box
from __init___parts.Brep import Brep
from __init___parts.CurveProxy import CurveProxy
from __init___parts.BrepEdge import BrepEdge
from __init___parts.Surface import Surface
from __init___parts.SurfaceProxy import SurfaceProxy
from __init___parts.BrepFace import BrepFace
from __init___parts.BrepLoop import BrepLoop
from __init___parts.BrepLoopType import BrepLoopType
from __init___parts.BrepRegion import BrepRegion
from __init___parts.BrepRegionFaceSide import BrepRegionFaceSide
from __init___parts.BrepSolidOrientation import BrepSolidOrientation
from __init___parts.BrepTrim import BrepTrim
from __init___parts.BrepTrimType import BrepTrimType
from __init___parts.Point import Point
from __init___parts.BrepVertex import BrepVertex
from __init___parts.Circle import Circle
from __init___parts.PlaneSurface import PlaneSurface
from __init___parts.ClippingPlaneSurface import ClippingPlaneSurface
from __init___parts.ComponentIndex import ComponentIndex
from __init___parts.ComponentIndexType import ComponentIndexType
from __init___parts.Cone import Cone
from __init___parts.Continuity import Continuity
from __init___parts.ControlPoint import ControlPoint
from __init___parts.CurveEnd import CurveEnd
from __init___parts.CurveEvaluationSide import CurveEvaluationSide
from __init___parts.CurveExtensionStyle import CurveExtensionStyle
from __init___parts.CurveKnotStyle import CurveKnotStyle
from __init___parts.CurveOffsetCornerStyle import CurveOffsetCornerStyle
from __init___parts.CurveOrientation import CurveOrientation
from __init___parts.CurveSimplifyOptions import CurveSimplifyOptions
from __init___parts.Cylinder import Cylinder
from __init___parts.DetailView import DetailView
from __init___parts.EdgeAdjacency import EdgeAdjacency
from __init___parts.Ellipse import Ellipse
from __init___parts.ExtrudeCornerType import ExtrudeCornerType
from __init___parts.Extrusion import Extrusion
from __init___parts.Hatch import Hatch
from __init___parts.InstanceDefinitionGeometry import InstanceDefinitionGeometry
from __init___parts.InstanceReferenceGeometry import InstanceReferenceGeometry
from __init___parts.Interpolator import Interpolator
from __init___parts.Interval import Interval
from __init___parts.IsoStatus import IsoStatus
from __init___parts.Leader import Leader
from __init___parts.Light import Light
from __init___parts.LightStyle import LightStyle
from __init___parts.Line import Line
from __init___parts.LinearDimension import LinearDimension
from __init___parts.LineCurve import LineCurve
from __init___parts.LoftType import LoftType
from __init___parts.Matrix import Matrix
from __init___parts.Mesh import Mesh
from __init___parts.MeshFace import MeshFace
from __init___parts.MeshingParameters import MeshingParameters
from __init___parts.MeshingParameterStyle import MeshingParameterStyle
from __init___parts.MeshPart import MeshPart
from __init___parts.MeshPoint import MeshPoint
from __init___parts.MeshType import MeshType
from __init___parts.MorphControl import MorphControl
from __init___parts.NurbsCurve import NurbsCurve
from __init___parts.NurbsSurface import NurbsSurface
from __init___parts.OrdinateDimension import OrdinateDimension
from __init___parts.Particle import Particle
from __init___parts.ParticleSystem import ParticleSystem
from __init___parts.PipeCapMode import PipeCapMode
from __init___parts.Plane import Plane
from __init___parts.PlaneFitResult import PlaneFitResult
from __init___parts.Point2d import Point2d
from __init___parts.Point2f import Point2f
from __init___parts.Point3d import Point3d
from __init___parts.Point3dGrid import Point3dGrid
from __init___parts.Point3f import Point3f
from __init___parts.Point4d import Point4d
from __init___parts.PointCloud import PointCloud
from __init___parts.PointCloudItem import PointCloudItem
from __init___parts.PointContainment import PointContainment
from __init___parts.PointFaceRelation import PointFaceRelation
from __init___parts.PolyCurve import PolyCurve
from __init___parts.Polyline import Polyline
from __init___parts.PolylineCurve import PolylineCurve
from __init___parts.Quaternion import Quaternion
from __init___parts.RadialDimension import RadialDimension
from __init___parts.Ray3d import Ray3d
from __init___parts.Rectangle3d import Rectangle3d
from __init___parts.RegionContainment import RegionContainment
from __init___parts.RevSurface import RevSurface
from __init___parts.RTree import RTree
from __init___parts.RTreeEventArgs import RTreeEventArgs
from __init___parts.SpaceMorph import SpaceMorph
from __init___parts.Sphere import Sphere
from __init___parts.SumSurface import SumSurface
from __init___parts.SurfaceCurvature import SurfaceCurvature
from __init___parts.SweepOneRail import SweepOneRail
from __init___parts.SweepTwoRail import SweepTwoRail
from __init___parts.TextDot import TextDot
from __init___parts.TextEntity import TextEntity
from __init___parts.TextJustification import TextJustification
from __init___parts.Torus import Torus
from __init___parts.Transform import Transform
from __init___parts.TransformSimilarityType import TransformSimilarityType
from __init___parts.Unroller import Unroller
from __init___parts.Vector2d import Vector2d
from __init___parts.Vector2f import Vector2f
from __init___parts.Vector3d import Vector3d
from __init___parts.Vector3f import Vector3f
from __init___parts.VolumeMassProperties import VolumeMassProperties
