class StylusPointProperties(object):
 """ Contains a System.Windows.Input.StylusPointProperty for each property that the WPF supports. """
 AltitudeOrientation=None
 AzimuthOrientation=None
 BarrelButton=None
 ButtonPressure=None
 Height=None
 NormalPressure=None
 PacketStatus=None
 PitchRotation=None
 RollRotation=None
 SecondaryTipButton=None
 SerialNumber=None
 SystemTouch=None
 TangentPressure=None
 TipButton=None
 TwistOrientation=None
 Width=None
 X=None
 XTiltOrientation=None
 Y=None
 YawRotation=None
 YTiltOrientation=None
 Z=None
 __all__=[
  'AltitudeOrientation',
  'AzimuthOrientation',
  'BarrelButton',
  'ButtonPressure',
  'Height',
  'NormalPressure',
  'PacketStatus',
  'PitchRotation',
  'RollRotation',
  'SecondaryTipButton',
  'SerialNumber',
  'SystemTouch',
  'TangentPressure',
  'TipButton',
  'TwistOrientation',
  'Width',
  'X',
  'XTiltOrientation',
  'Y',
  'YawRotation',
  'YTiltOrientation',
  'Z',
 ]

